### PR TITLE
Renamed forge constant to neo_forge

### PR DESCRIPTION
**Pull request by EwyBoy**
Renamed the `forge` constants in `gradle.properties` and updated some comments.

| Old                  | New                     |
|----------------------|-------------------------|
| `forge_version`      | `neo_forge_version`     |
| `forge_version_range`| `neo_forge_version_range`|

### CODE REVIEW

**Comment by pupnewfster** [comment]
Personally I think maybe naming them `neo_version` and `neo_version_range` might be better? As they are effectively the same level of conciseness, but are a bit shorter so easier to read at a glance

**Comment by EwyBoy** [comment]
I agree with you @pupnewfster. I was just not sure what the branding / naming convention NeoForged is targeting.
Are we going with plane and simple Neo for everything like the mod_id etc?

**Comment by cpw** [comment]
neo is fine - as is neoforge. neoforged is generally not ok, because that's the name of the project as a whole. neo/neoforge are the primary _product_.

**Comment by EwyBoy** [comment]
Renamed:

| Old                  | New                     |
|----------------------|-------------------------|
| `forge_version`      | `neo_version`     |
| `forge_version_range`| `neo_version_range`|

**Comment by pupnewfster** [comment]
Seems fine to me, though it probably is worth given the similar/close nature to also update: https://github.com/neoforged/MDK/blob/main/src/main/resources/META-INF/mods.toml#L23 to point to https://docs.neoforged.net/docs/misc/updatechecker/

**Comment by EwyBoy** [comment]
Updated the update checker URL and the name field in the `settings.gradle` to have the new organization name.

Not sure if we have a new URL for this or if it should stay?
https://github.com/neoforged/MDK/blob/efbe53492e072d63b239d892889752b31185fdb7/gradle.properties#L31

**Comment by pupnewfster** [comment]
https://github.com/neoforged/NeoForm/blob/main/Mojang.md would probably be the new URL for the one you are asking about

**Comment by EwyBoy** [comment]
Is this still required? If yes, rename?
https://github.com/neoforged/MDK/blob/efbe53492e072d63b239d892889752b31185fdb7/.gitignore#L24-L25

**Comment by cpw** [comment]
> Is this still required? If yes, rename?
> 
> https://github.com/neoforged/MDK/blob/efbe53492e072d63b239d892889752b31185fdb7/.gitignore#L24-L25

Very unlikely - I believe it's an artifact of the old way of building MDK.

**Comment by EwyBoy** [comment]
Ready for merge?

**Review by pupnewfster — APPROVED** [review]

**Pull request merged**
