### PR TITLE
Make the MDK automatically update to the latest NeoGradle

### PR DESCRIPTION
**Pull request by Nekretaur**

### CODE REVIEW

**Comment by TelepathicGrunt** [comment]
I am not sure this is a good idea. If Neoforge releases a breaking change, the MDK would be broken until someone makes a PR to fix it. It also means any mod using the MDK as a base will suddenly break one day and people won't know why. Updating neoforge should be a explicit action that the modder takes so they know if they are experiencing a breaking change or not

**Comment by TelepathicGrunt** [comment]
Unless of course, NeoGradle breaking changes are codified into the minor version number. Then `7.0.+` would be a better idea instead of `7.+`

**Comment by Nekretaur** [comment]
Both achieve the same thing, so it isn't a big issue.

**Comment by Matyrobbrt** [comment]
Due to the way the build and configuration cache behaves, any update to plugins will also cause an entire decomp/recomp cycle. So this will make people run that setup all over again for seemingly random reasons. Not to mention that reproducibility is also broken by the use of ranges in plugin versions, which gradle discourages. NG is rather stable right now and updates aren't that frequent. If people run into issues they can ask, and if it's fixed already we will tell them to update.

**Pull request closed without merging**
