### PR TITLE
Add the link to the Kotlin DSL MDK for NeoForge

### PR DESCRIPTION
**Pull request by Nekretaur**

### CODE REVIEW

**Comment by marchermans** [comment]
No sorry. We won't be linking to be external uncontrolled repositories

**Comment by marchermans** [comment]
No sorry. We won't be linking to be external uncontrolled repositories

**Comment by Nekretaur** [comment]
what if I transfer ownership?

**Comment by marchermans** [comment]
At the moment that would not really be usefull. Neoforge has no kotlin libraries. So it would still be us linking to other people.

Right now the kotlin infrastructure is community driven.

**Pull request closed without merging**
